"""empty message

Revision ID: 1347692f1403
Revises: 
Create Date: 2022-05-07 20:15:30.464482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1347692f1403'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KCSE_Results',
    sa.Column('KCSE_ID', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=16), nullable=False),
    sa.Column('A', sa.Integer(), nullable=True),
    sa.Column('A_minus', sa.Integer(), nullable=True),
    sa.Column('B_plus', sa.Integer(), nullable=True),
    sa.Column('B', sa.Integer(), nullable=True),
    sa.Column('B_minus', sa.Integer(), nullable=True),
    sa.Column('C_plus', sa.Integer(), nullable=True),
    sa.Column('C', sa.Integer(), nullable=True),
    sa.Column('C_minus', sa.Integer(), nullable=True),
    sa.Column('D_plus', sa.Integer(), nullable=True),
    sa.Column('D', sa.Integer(), nullable=True),
    sa.Column('D_minus', sa.Integer(), nullable=True),
    sa.Column('E', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('KCSE_ID')
    )
    op.create_table('book_author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('residential_address', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('phone_no', sa.String(length=32), nullable=True),
    sa.Column('associated_image', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_index(op.f('ix_book_author_author_id'), 'book_author', ['author_id'], unique=False)
    op.create_table('book_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_book_category_category_id'), 'book_category', ['category_id'], unique=False)
    op.create_table('club',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.String(length=128), nullable=False),
    sa.Column('year_founded', sa.String(length=32), nullable=False),
    sa.Column('mission', sa.Text(), nullable=False),
    sa.Column('vision', sa.Text(), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('email_address', sa.String(length=128), nullable=False),
    sa.Column('about_us', sa.Text(), nullable=False),
    sa.Column('associated_image', sa.String(length=255), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('club_id'),
    sa.UniqueConstraint('club_name')
    )
    op.create_table('exam',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('exam_title', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_table('hospital',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(length=128), nullable=False),
    sa.Column('location_address', sa.String(length=128), nullable=True),
    sa.Column('email_address', sa.String(length=128), nullable=True),
    sa.Column('phone_no', sa.String(length=32), nullable=True),
    sa.Column('associated_image', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_table('house',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('house_title', sa.String(length=64), nullable=False),
    sa.Column('year_established', sa.String(length=32), nullable=False),
    sa.Column('opened_by', sa.String(length=128), nullable=False),
    sa.Column('sister_house', sa.String(length=64), nullable=False),
    sa.Column('motto', sa.String(length=128), nullable=False),
    sa.Column('bed_cover', sa.String(length=64), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('house_id')
    )
    op.create_table('medication_stock',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('units', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_table('nurse',
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('national_id_no', sa.Integer(), nullable=False),
    sa.Column('residential_address', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('phone_no', sa.String(length=32), nullable=True),
    sa.Column('associated_image', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nurse_id')
    )
    op.create_table('obc_event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_scheduled', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('associated_image', sa.String(length=128), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('publisher',
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('publisher_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('publisher_id')
    )
    op.create_index(op.f('ix_publisher_publisher_name'), 'publisher', ['publisher_name'], unique=False)
    op.create_table('san_room',
    sa.Column('san_room_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=32), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('san_room_id')
    )
    op.create_table('subject',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_title', sa.String(length=64), nullable=False),
    sa.Column('associated_image', sa.String(length=255), nullable=True),
    sa.Column('HOS', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(length=128), nullable=False),
    sa.Column('phone_no', sa.String(length=32), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('teacher',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('TSC_no', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('national_id_no', sa.Integer(), nullable=False),
    sa.Column('residential_address', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('phone_no', sa.String(length=32), nullable=True),
    sa.Column('associated_image', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('achievement',
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('year_achieved', sa.String(length=32), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.club_id'], ),
    sa.PrimaryKeyConstraint('achievement_id')
    )
    op.create_table('bed',
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=32), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('san_room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['san_room_id'], ['san_room.san_room_id'], ),
    sa.PrimaryKeyConstraint('bed_id')
    )
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('year_of_production', sa.String(length=4), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('book_category_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_category_id'], ['book_category.category_id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.publisher_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_book_book_id'), 'book', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_year_of_production'), 'book', ['year_of_production'], unique=False)
    op.create_table('classroom',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('class_teacher', sa.Integer(), nullable=True),
    sa.Column('associated_image', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=128), nullable=True),
    sa.Column('instagram', sa.String(length=128), nullable=True),
    sa.Column('twitter', sa.String(length=128), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_teacher'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('club_schedule',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.club_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('current_stock',
    sa.Column('current_stock_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['medication_stock.stock_id'], ),
    sa.PrimaryKeyConstraint('current_stock_id')
    )
    op.create_table('doctor',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('national_id_no', sa.Integer(), nullable=False),
    sa.Column('residential_address', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('phone_no', sa.String(length=32), nullable=True),
    sa.Column('associated_image', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_scheduled', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('associated_image', sa.String(length=128), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.club_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('founder',
    sa.Column('founder_id', sa.Integer(), nullable=False),
    sa.Column('names', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('email_address', sa.String(length=128), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.club_id'], ),
    sa.PrimaryKeyConstraint('founder_id')
    )
    op.create_table('hospital_services',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('medication',
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('dosage', sa.String(length=16), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['medication_stock.stock_id'], ),
    sa.PrimaryKeyConstraint('medication_id')
    )
    op.create_table('obc',
    sa.Column('obc_id', sa.Integer(), nullable=False),
    sa.Column('adm_no', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('phone_no', sa.String(length=32), nullable=False),
    sa.Column('residential_address', sa.String(length=255), nullable=False),
    sa.Column('profession', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('associated_image', sa.String(length=128), nullable=True),
    sa.Column('year', sa.String(length=16), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.house_id'], ),
    sa.PrimaryKeyConstraint('obc_id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('phone_no')
    )
    op.create_index(op.f('ix_obc_adm_no'), 'obc', ['adm_no'], unique=False)
    op.create_table('publisher_contact',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('contact_detail', sa.String(length=32), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.publisher_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('related_book',
    sa.Column('related_book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('year_of_production', sa.String(length=4), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('book_author_id', sa.Integer(), nullable=False),
    sa.Column('book_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_author_id'], ['book_author.author_id'], ),
    sa.ForeignKeyConstraint(['book_category_id'], ['book_category.category_id'], ),
    sa.PrimaryKeyConstraint('related_book_id')
    )
    op.create_table('student',
    sa.Column('admission_no', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('email_address', sa.String(length=128), nullable=True),
    sa.Column('phone_no', sa.String(length=32), nullable=True),
    sa.Column('nemis', sa.String(length=32), nullable=True),
    sa.Column('residence', sa.String(length=128), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('associated_image', sa.String(length=255), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.house_id'], ),
    sa.PrimaryKeyConstraint('admission_no'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('nemis'),
    sa.UniqueConstraint('phone_no')
    )
    op.create_table('author_assignment',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['book_author.author_id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('book_assignment',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.admission_no'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('doctor_speciality',
    sa.Column('doc_speciality_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.PrimaryKeyConstraint('doc_speciality_id')
    )
    op.create_table('exam_assignment',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('admission_no', sa.Integer(), nullable=True),
    sa.Column('maths', sa.Integer(), nullable=True),
    sa.Column('english', sa.Integer(), nullable=True),
    sa.Column('kiswahili', sa.Integer(), nullable=True),
    sa.Column('biology', sa.Integer(), nullable=True),
    sa.Column('chemistry', sa.Integer(), nullable=True),
    sa.Column('physics', sa.Integer(), nullable=True),
    sa.Column('business', sa.Integer(), nullable=True),
    sa.Column('art', sa.Integer(), nullable=True),
    sa.Column('music', sa.Integer(), nullable=True),
    sa.Column('computer', sa.Integer(), nullable=True),
    sa.Column('agriculture', sa.Integer(), nullable=True),
    sa.Column('electricity', sa.Integer(), nullable=True),
    sa.Column('french', sa.Integer(), nullable=True),
    sa.Column('german', sa.Integer(), nullable=True),
    sa.Column('geography', sa.Integer(), nullable=True),
    sa.Column('CRE', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admission_no'], ['student.admission_no'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.exam_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('medical_record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('nurse_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurse.nurse_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.admission_no'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('obc_achievement',
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('year', sa.String(length=16), nullable=False),
    sa.Column('obc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['obc_id'], ['obc.obc_id'], ),
    sa.PrimaryKeyConstraint('achievement_id')
    )
    op.create_table('punishment',
    sa.Column('punishment_id', sa.Integer(), nullable=False),
    sa.Column('offence', sa.String(length=1024), nullable=False),
    sa.Column('punishment', sa.String(length=255), nullable=False),
    sa.Column('overseer', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('admission_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admission_no'], ['student.admission_no'], ),
    sa.PrimaryKeyConstraint('punishment_id')
    )
    op.create_table('speaker',
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('email_address', sa.String(length=128), nullable=False),
    sa.Column('profession', sa.String(length=128), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('speaker_id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('subject_assignment',
    sa.Column('subject_assignment_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['classroom.class_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('subject_assignment_id')
    )
    op.create_table('class_assignment',
    sa.Column('class_assignment_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_assignment_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classroom.class_id'], ),
    sa.ForeignKeyConstraint(['subject_assignment_id'], ['subject_assignment.subject_assignment_id'], ),
    sa.PrimaryKeyConstraint('class_assignment_id')
    )
    op.create_table('diagnosis',
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['medical_record.record_id'], ),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    op.create_table('inpatient_admission',
    sa.Column('inpatient_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('bed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bed_id'], ['bed.bed_id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['medical_record.record_id'], ),
    sa.PrimaryKeyConstraint('inpatient_id')
    )
    op.create_table('medical_intake',
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('time_taken', sa.DateTime(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['medical_record.record_id'], ),
    sa.PrimaryKeyConstraint('intake_id')
    )
    op.create_table('reference',
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['medical_record.record_id'], ),
    sa.PrimaryKeyConstraint('reference_id')
    )
    op.create_table('reference_medication',
    sa.Column('ref_med_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('dosage', sa.String(length=16), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.reference_id'], ),
    sa.PrimaryKeyConstraint('ref_med_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_medication')
    op.drop_table('reference')
    op.drop_table('medical_intake')
    op.drop_table('inpatient_admission')
    op.drop_table('diagnosis')
    op.drop_table('class_assignment')
    op.drop_table('subject_assignment')
    op.drop_table('speaker')
    op.drop_table('punishment')
    op.drop_table('obc_achievement')
    op.drop_table('medical_record')
    op.drop_table('exam_assignment')
    op.drop_table('doctor_speciality')
    op.drop_table('book_assignment')
    op.drop_table('author_assignment')
    op.drop_table('student')
    op.drop_table('related_book')
    op.drop_table('publisher_contact')
    op.drop_index(op.f('ix_obc_adm_no'), table_name='obc')
    op.drop_table('obc')
    op.drop_table('medication')
    op.drop_table('hospital_services')
    op.drop_table('founder')
    op.drop_table('event')
    op.drop_table('doctor')
    op.drop_table('current_stock')
    op.drop_table('club_schedule')
    op.drop_table('classroom')
    op.drop_index(op.f('ix_book_year_of_production'), table_name='book')
    op.drop_index(op.f('ix_book_book_id'), table_name='book')
    op.drop_table('book')
    op.drop_table('bed')
    op.drop_table('achievement')
    op.drop_table('teacher')
    op.drop_table('subject')
    op.drop_table('san_room')
    op.drop_index(op.f('ix_publisher_publisher_name'), table_name='publisher')
    op.drop_table('publisher')
    op.drop_table('obc_event')
    op.drop_table('nurse')
    op.drop_table('medication_stock')
    op.drop_table('house')
    op.drop_table('hospital')
    op.drop_table('exam')
    op.drop_table('club')
    op.drop_index(op.f('ix_book_category_category_id'), table_name='book_category')
    op.drop_table('book_category')
    op.drop_index(op.f('ix_book_author_author_id'), table_name='book_author')
    op.drop_table('book_author')
    op.drop_table('KCSE_Results')
    # ### end Alembic commands ###
