"""empty message

Revision ID: 8c587e593f95
Revises: 1347692f1403
Create Date: 2022-05-17 14:39:28.349808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c587e593f95'
down_revision = '1347692f1403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport',
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('sport_name', sa.String(length=128), nullable=False),
    sa.Column('year_established', sa.String(length=8), nullable=True),
    sa.Column('associated_image', sa.String(length=128), nullable=True),
    sa.Column('patron_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patron_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('sport_id')
    )
    op.create_index(op.f('ix_sport_sport_name'), 'sport', ['sport_name'], unique=True)
    op.create_table('sport_coach',
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email_address', sa.String(length=128), nullable=False),
    sa.Column('phone_no', sa.String(length=32), nullable=False),
    sa.Column('residential_address', sa.String(length=128), nullable=True),
    sa.Column('associated_image', sa.String(length=255), nullable=True),
    sa.Column('year_appointed', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.sport_id'], ),
    sa.PrimaryKeyConstraint('coach_id')
    )
    op.create_table('sport_team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=128), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.sport_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('sport_event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('associated_image', sa.String(length=128), nullable=True),
    sa.Column('date_held', sa.Date(), nullable=False),
    sa.Column('associated_report', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['student.admission_no'], ),
    sa.ForeignKeyConstraint(['team_id'], ['sport_team.team_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('sport_notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('associated_image', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sport_coach.coach_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('sport_position',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['sport_team.team_id'], ),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('sport_assignment',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('associated_image', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['sport_position.position_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.admission_no'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sport_assignment')
    op.drop_table('sport_position')
    op.drop_table('sport_notification')
    op.drop_table('sport_event')
    op.drop_table('sport_team')
    op.drop_table('sport_coach')
    op.drop_index(op.f('ix_sport_sport_name'), table_name='sport')
    op.drop_table('sport')
    # ### end Alembic commands ###
